server:
  port: 8000
  servlet:
    contextPath: /game-store/app/api/v1
spring:
  datasource:
    url: jdbc:h2:file:db\game_store
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernateDialect: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update